server {
    listen 80;
    server_name edge.gudman.xyz;
    include /etc/nginx/snippets/acme-challenge.conf;

    root /opt/fixfirst-edge/landing;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}
